services:
  - type: worker
    name: rushsearchbot-worker
    env: python
    plan: free         # of standard als je betaalde uptime wilt
    region: frankfurt  # kies jouw regio als string; laat weg als je via UI kiest
    autoDeploy: false
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false        # waarde zet je in de Render UI (secrets)
      - key: PANEL_CHANNEL_ID
        value: "1404949428040896613"
      - key: LOG_LEVEL
        value: "INFO"
      - key: BACKOFF_MIN
        value: "300"
      - key: BACKOFF_MAX
        value: "900"